- include_tasks: node.yml
- include_tasks: wav2png.yml

- name: ensure warmup user exists
  user:
    name: "{{ warmup_user }}"
    state: present
    create_home: true
  register: warmup_user_info

- name: clone warmup repo
  git:
    repo: "{{ warmup_repo }}"
    dest: "{{ warmup_user_info.home }}/warmup"
  become: true
  become_user: "{{ warmup_user }}"
  register: warmup_repo

- name: install warmup server
  command:
    chdir: "{{ warmup_user_info.home }}/warmup"
    cmd: "npm install"
    creates: "{{ warmup_user_info.home }}/warmup/node_modules"
  become: true
  become_user: "{{ warmup_user }}"

- name: install warmup client
  command:
    chdir: "{{ warmup_user_info.home }}/warmup"
    cmd: "node_modules/.bin/bower install"
    creates: "{{ warmup_user_info.home }}/warmup/bower_components"
  become: true
  become_user: "{{ warmup_user }}"

- name: create warmup config
  template:
    src: config.js.j2
    dest: "{{ warmup_user_info.home }}/warmup/config.js"
  become: true
  become_user: "{{ warmup_user }}"

- name: create warmup.service
  copy:
    dest: /etc/systemd/system/warmup.service
    content: |
      [Unit]
      Description=MPD Frontend

      Requires=mpd.service
      After=mpd.service

      StartLimitIntervalSec=0
      StartLimitBurst=0

      [Service]
      User={{ warmup_user }}
      WorkingDirectory={{ warmup_user_info.home }}
      ExecStart=/usr/bin/node warmup
      Restart=always

      [Install]
      WantedBy=multi-user.target
  register: warmup_service

- name: reload systemd
  command: systemctl daemon-reload
  when: warmup_service.changed

- name: start warmup
  systemd:
    name: warmup.service
    state: started
    enabled: true
